---
- name: Get release
  command: lsb_release -cs
  register: lsb_release
  delegate_to: 127.0.0.1

- name: Add Node.js repository
  apt_repository:
    filename: nodesource
    repo: "{{ repo }}"

- name: Install Node.js
  apt:
    name: nodejs
...