---
docker_ce_key: https://download.docker.com/linux/ubuntu/gpg
docker_ce_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ release }} stable"
docker_compose_repo_prefix: https://github.com/docker/compose/releases/download/1.16.1/docker-compose
docker_compose_repo: "{{ docker_compose_repo_prefix }}-{{ uname_s }}-{{ uname_m }}"
docker_compose_bin: /usr/local/bin/docker-compose
...