---
- name: Install Git
  apt:
    name: git

- name: Configure Git name
  command: "git config --global user.name {{ github_name }}"

- name: Configure Git email
  command: "git config --global user.email {{ email }}"

- name: Enable automatic color
  command: git config --global color.ui auto

- name: Clone my repository
  git:
    repo: "{{ lookup('ini', 'url section=repo file={{ playbook_dir }}/git.ini') }}"
    dest: "{{ lookup('ini', 'dir section=repo file={{ playbook_dir }}/git.ini') }}"

- name: Create database
  become: yes
  become_method: sudo
  command: docker-compose run web yarn run sequelize -- db:create
  args:
    chdir: "{{ lookup('ini', 'dir section=repo file={{ playbook_dir }}/git.ini') }}"

- name: Migrate
  become: yes
  become_method: sudo
  command: docker-compose run web yarn run db:migrate
  args:
    chdir: "{{ lookup('ini', 'dir section=repo file={{ playbook_dir }}/git.ini') }}"
...