---
- name: Install GDebi
  apt:
    name: gdebi

- name: Download deb file
  get_url:
    url: "{{ url }}"
    dest: "{{ file }}"
    force: yes

- name: Install Chrome
  become: yes
  become_method: sudo
  command: "gdebi -n {{ file }}"

- name: Delete deb file
  file:
    path: "{{ file }}"
    state: absent
...