---
- name: Install vim
  apt:
    name: vim

- name: Get username
  command: whoami
  register: whoami
  delegate_to: 127.0.0.1

- name: Download .vimrc
  get_url:
    url: "{{ url }}"
    dest: "/home/{{ whoami.stdout }}/.vimrc"
    force: yes
...